export const ROLE_MENU_ITEMS = {
  ADMIN: [
    { label: "Tableau de Bord", to: "/dashboard/admin" },
    { label: "Produits", to: "/inventory" },
    { label: "Mouvements Stock", to: "/stock-movements" },
    { label: "Notifications", to: "/notifications" },
    { label: "Categories", to: "/categories" },
    { label: "Clients", to: "/clients" },
    { label: "Devis", to: "/devis" },
    { label: "Commandes", to: "/commandes" },
    { label: "Bons de commande", to: "/bon-commandes" },
    { label: "Factures", to: "/factures" },
    { label: "Paiements", to: "/paiements" },
    { label: "Transporteurs", to: "/transporters" },
    { label: "Livraisons", to: "/livraisons" },
    { label: "Fournisseurs", to: "/suppliers" },
    { label: "Achats", to: "/achats" },
    { label: "Budgets", to: "/budgets" },
    { label: "Taux de change", to: "/currency-rates" },
    { label: "Objectifs", to: "/objectifs" },
    { label: "RH - Employes", to: "/rh/employees" },
    { label: "RH - Departements", to: "/rh/departments" },
    { label: "RH - Postes", to: "/rh/positions" },
    { label: "RH - Contrats", to: "/rh/contracts" },
    { label: "RH - Conges", to: "/rh/leaves" },
    { label: "RH - Documents", to: "/rh/documents" },
    { label: "RH - Evaluations", to: "/rh/evaluations" },
    { label: "RH - Formations", to: "/rh/trainings" },
    { label: "RH - Paie", to: "/rh/payrolls" },
    { label: "RH - Pilotage", to: "/rh/insights" },
    { label: "Profil", to: "/profile" },
    { label: "Deconnexion", to: "/logout" },
  ],
  MANAGER: [
    { label: "Tableau de Bord", to: "/dashboard/manager" },
    { label: "Clients", to: "/clients" },
    { label: "Devis", to: "/devis" },
    { label: "Commandes", to: "/commandes" },
    { label: "Factures", to: "/factures" },
    { label: "Notifications", to: "/notifications" },
    { label: "RH - Pilotage", to: "/rh/insights" },
    { label: "Profil", to: "/profile" },
    { label: "Deconnexion", to: "/logout" },
  ],
  SALES_MANAGER: [
    { label: "Tableau de Bord", to: "/dashboard/sales" },
    { label: "Clients", to: "/clients" },
    { label: "Devis", to: "/devis" },
    { label: "Commandes", to: "/commandes" },
    { label: "Factures", to: "/factures" },
    { label: "Paiements", to: "/paiements" },
    { label: "Taux de change", to: "/currency-rates" },
    { label: "Notifications", to: "/notifications" },
    { label: "Profil", to: "/profile" },
    { label: "Deconnexion", to: "/logout" },
  ],
  PROCUREMENT_MANAGER: [
    { label: "Tableau de Bord", to: "/dashboard/procurement" },
    { label: "Fournisseurs", to: "/suppliers" },
    { label: "Achats", to: "/achats" },
    { label: "Mouvements Stock", to: "/stock-movements" },
    { label: "Notifications", to: "/notifications" },
    { label: "Taux de change", to: "/currency-rates" },
    { label: "Produits", to: "/inventory" },
    { label: "Categories", to: "/categories" },
    { label: "Profil", to: "/profile" },
    { label: "Deconnexion", to: "/logout" },
  ],
  HR_MANAGER: [
    { label: "Tableau de Bord", to: "/dashboard/hr" },
    { label: "RH - Employes", to: "/rh/employees" },
    { label: "RH - Departements", to: "/rh/departments" },
    { label: "RH - Postes", to: "/rh/positions" },
    { label: "RH - Contrats", to: "/rh/contracts" },
    { label: "RH - Conges", to: "/rh/leaves" },
    { label: "RH - Documents", to: "/rh/documents" },
    { label: "RH - Evaluations", to: "/rh/evaluations" },
    { label: "RH - Formations", to: "/rh/trainings" },
    { label: "RH - Paie", to: "/rh/payrolls" },
    { label: "RH - Pilotage", to: "/rh/insights" },
    { label: "Notifications", to: "/notifications" },
    { label: "Profil", to: "/profile" },
    { label: "Deconnexion", to: "/logout" },
  ],
  FINANCE_MANAGER: [
    { label: "Tableau de Bord", to: "/dashboard/finance" },
    { label: "Factures", to: "/factures" },
    { label: "Paiements", to: "/paiements" },
    { label: "Achats", to: "/achats" },
    { label: "Taux de change", to: "/currency-rates" },
    { label: "Budgets", to: "/budgets" },
    { label: "Objectifs", to: "/objectifs" },
    { label: "RH - Paie", to: "/rh/payrolls" },
    { label: "Notifications", to: "/notifications" },
    { label: "Profil", to: "/profile" },
    { label: "Deconnexion", to: "/logout" },
  ],
  LOGISTICS_MANAGER: [
    { label: "Tableau de Bord", to: "/dashboard/logistics" },
    { label: "Transporteurs", to: "/transporters" },
    { label: "Livraisons", to: "/livraisons" },
    { label: "Achats", to: "/achats" },
    { label: "Commandes", to: "/commandes" },
    { label: "Mouvements Stock", to: "/stock-movements" },
    { label: "Notifications", to: "/notifications" },
    { label: "Produits", to: "/inventory" },
    { label: "Profil", to: "/profile" },
    { label: "Deconnexion", to: "/logout" },
  ],
  USER: [
    { label: "Tableau de Bord", to: "/dashboard/user" },
    { label: "Profil", to: "/profile" },
    { label: "Mes Ventes", to: "/sales" },
    { label: "Mes Achats", to: "/achats" },
    { label: "Mes mouvements", to: "/sales/new" },
    { label: "Notifications", to: "/notifications" },
    { label: "Deconnexion", to: "/logout" },
  ],
};
