export const DATA_TABLE_DEFAULTS = {
  title: "",
  rows: [],
  columns: [],
  loading: false,
  error: "",
  enablePagination: true,
  initialPage: 1,
  initialPageSize: 10,
  pageSizeOptions: [5, 10, 20, 50],
  loadingMessage: "Chargement...",
  emptyMessage: "Aucune donnée disponible.",
  sectionClassName: "p-card p-card--table",
  titleClassName: "p-table-section__title",
  tableClassName: "p-table",
  stateRowClassName: "p-data-table__state",
  errorRowClassName: "p-data-table__state--error",
  getRowKey: (row, index) => row?.id ?? row?.reference ?? index,
};
