export const LOGIN_FORM_DEFAULTS = {
  emailLabel: "Adresse e-mail",
  passwordLabel: "Mot de passe",
  emailPlaceholder: "Entrez votre nom d'utilisateur",
  passwordPlaceholder: "Entrez votre mot de passe",
  emailValue: "",
  passwordValue: "",
  buttonText: "Se connecter",
  onSubmit: () => {},
  onEmailChange: () => {},
  onPasswordChange: () => {},
  error: "",
  success: "",
  isLoading: false,
  customClassName: "",
  emailFieldProps: {
    customClassName: "p-field",
    labelClassName: "p-field__label",
    errorClassName: "p-field__error",
  },
  passwordFieldProps: {
    customClassName: "p-field",
    labelClassName: "p-field__label",
    errorClassName: "p-field__error",
  },
  submitButtonClassName: "",
  errorClassName: "p-login__alert",
  successClassName: "p-login__success",
  showLinks: true,
  signUpLink: "/signup",
  resetPasswordLink: "/forget-password",
};
