export const OVERVIEW_DEFAULTS = {
  containerClassName: "p-overview",
  itemSectionTitle: "Informations",
  movementsSectionTitle: "Mouvements Récents",
  infoRows: [],
  movements: [],
  tableSections: [],
  movementLimit: 10,
  loadingText: "Chargement...",
  emptyMovementsText: "Aucun mouvement trouvé.",
  cardClassName: "p-overview__card",
  cardTitleClassName: "p-overview__card-title",
  cardBodyClassName: "p-overview__card-body",
  infoRowClassName: "p-overview__info-row",
  infoLabelClassName: "p-overview__info-label",
  infoValueClassName: "p-overview__info-value",
  movementsContainerClassName: "p-overview__movements-container",
  movementColumns: [
    { key: "type", header: "Type" },
    { key: "date", header: "Date" },
    { key: "quantity", header: "Quantité" },
    { key: "reference", header: "Référence" },
  ],
  movementsTableSectionClassName: "p-overview__movements-table-section",
  movementsTableClassName: "p-overview__movements-table",
  movementsTableStateClassName: "p-overview__movements-table-state",
  movementsTableErrorClassName: "p-overview__movements-error",
  movementErrorClassName: "p-overview__movements-error",
  getMovementKey: (movement, index) => movement?.id || index,
};
