export const PRODUCT_OVERVIEW_DEFAULTS = {
  product: null,
  movements: [],
  movementsLoading: false,
  movementsError: "",
  containerClassName: "p-product-detail__layout",
  productSectionTitle: "Informations du Produit",
  movementsSectionTitle: "Mouvements Récents",
  infoRows: [],
  movementLimit: 8,
  loadingText: "Chargement des mouvements...",
  emptyMovementsText: "Aucun mouvement enregistré.",
  cardClassName: "p-card p-detail-card",
  cardTitleClassName: "p-detail-card__title",
  cardBodyClassName: "p-detail-card__body",
  infoRowClassName: "p-detail-info__row",
  infoLabelClassName: "p-detail-info__label",
  infoValueClassName: "p-detail-info__value",
  movementsContainerClassName: "p-detail-movements",
  movementColumns: [
    { key: "type", header: "Type" },
    { key: "qty", header: "Quantité" },
    { key: "date", header: "Date" },
  ],
  movementsTableSectionClassName: "",
  movementsTableClassName: "p-detail-movements__table",
  movementsTableStateClassName: "p-product-page__state",
  movementsTableErrorClassName: "p-product-page__state--error",
  movementErrorClassName: "p-product-page__state--error",
  getMovementKey: (movement, index) => `${movement?.reference || "movement"}-${movement?.date || index}`,
  renderMovementRow: null,
};
