export const RESET_PASSWORD_FORM_DEFAULTS = {
  newPasswordLabel: "Nouveau mot de passe",
  confirmPasswordLabel: "Confirmer le mot de passe",
  newPasswordPlaceholder: "Entrez votre nouveau mot de passe",
  confirmPasswordPlaceholder: "Confirmez votre nouveau mot de passe",
  buttonText: "Réinitialiser le mot de passe",
  onSubmit: () => {},
  newPasswordValue: "",
  confirmPasswordValue: "",
  onNewPasswordChange: () => {},
  onConfirmPasswordChange: () => {},
  error: "",
  success: "",
  isLoading: false,
  customClassName: "",
  newPasswordFieldProps: {
    customClassName: "p-field",
    labelClassName: "p-field__label",
    errorClassName: "p-field__error",
  },
  confirmPasswordFieldProps: {
    customClassName: "p-field",
    labelClassName: "p-field__label",
    errorClassName: "p-field__error",
  },
  submitButtonClassName: "",
  errorClassName: "p-login__alert",
  successClassName: "p-login__success",
};
