import { SIGNUP_ROLE_OPTIONS } from "../../../constants/roles";

export const SIGNUP_FORM_DEFAULTS = {
  firstNameLabel: "Prénom",
  lastNameLabel: "Nom",
  emailLabel: "Adresse e-mail",
  passwordLabel: "Mot de passe",
  confirmPasswordLabel: "Confirmer le mot de passe",
  roleLabel: "Rôle",
  imageLabel: "Photo de profil",
  firstNamePlaceholder: "Entrez votre prénom",
  lastNamePlaceholder: "Entrez votre nom",
  emailPlaceholder: "Entrez votre adresse e-mail",
  passwordPlaceholder: "Minimum 8 caractères",
  confirmPasswordPlaceholder: "Confirmez votre mot de passe",
  buttonText: "S'inscrire",
  onSubmit: () => {},
  firstNameValue: "",
  lastNameValue: "",
  emailValue: "",
  passwordValue: "",
  confirmPasswordValue: "",
  roleValue: "USER",
  onFirstNameChange: () => {},
  onLastNameChange: () => {},
  onEmailChange: () => {},
  onPasswordChange: () => {},
  onConfirmPasswordChange: () => {},
  onRoleChange: () => {},
  onImageChange: () => {},
  imageValue: undefined,
  error: "",
  customClassName: "",
  firstNameFieldProps: {
    customClassName: "p-field",
    labelClassName: "p-field__label",
    errorClassName: "p-field__error",
  },
  lastNameFieldProps: {
    customClassName: "p-field",
    labelClassName: "p-field__label",
    errorClassName: "p-field__error",
  },
  emailFieldProps: {
    customClassName: "p-field",
    labelClassName: "p-field__label",
    errorClassName: "p-field__error",
  },
  passwordFieldProps: {
    customClassName: "p-field",
    labelClassName: "p-field__label",
    errorClassName: "p-field__error",
  },
  confirmPasswordFieldProps: {
    customClassName: "p-field",
    labelClassName: "p-field__label",
    errorClassName: "p-field__error",
  },
  roleFieldProps: {
    customClassName: "p-field",
    labelClassName: "p-field__label",
    errorClassName: "p-field__error",
  },
  imageFieldProps: {
    customClassName: "p-field",
    labelClassName: "p-field__label",
    errorClassName: "p-field__error",
  },
  submitButtonClassName: "",
  errorClassName: "p-login__alert",
  roles: SIGNUP_ROLE_OPTIONS,
};
