export const SUPPLIER_OVERVIEW_DEFAULTS = {
  containerClassName: "p-supplier-overview",
  supplierSectionTitle: "Informations du Fournisseur",
  movementsSectionTitle: "Achats Récents",
  infoRows: [
    { label: "Prénom", key: "firstName" },
    { label: "Nom", key: "lastName" },
    { label: "Email", key: "email" },
    { label: "Téléphone", key: "phone" },
    { label: "Ville", key: "city" },
    { label: "Pays", key: "country" },
    { label: "Adresse", key: "address" },
    { label: "Matricule Fiscale", key: "matriculeFiscale" },
    { label: "Créé", key: "createdAt" },
    { label: "Modifié", key: "updatedAt" },
  ],
  movementLimit: 10,
  loadingText: "Chargement des achats...",
  emptyMovementsText: "Aucun achat trouvé pour ce fournisseur.",
  cardClassName: "p-supplier-overview__card",
  cardTitleClassName: "p-supplier-overview__card-title",
  cardBodyClassName: "p-supplier-overview__card-body",
  infoRowClassName: "p-supplier-overview__info-row",
  infoLabelClassName: "p-supplier-overview__info-label",
  infoValueClassName: "p-supplier-overview__info-value",
  movementsContainerClassName: "p-supplier-overview__movements-container",
  movementColumns: [
    { key: "purchaseNumber", header: "NumeroAchat" },
    { key: "date", header: "Date" },
    { key: "statusLabel", header: "Statut" },
  ],
  movementsTableSectionClassName: "o-movements",
  movementsTableClassName: "o-movements__table p-supplier-overview__movements-table",
  movementsTableStateClassName: "p-supplier-overview__movements-table-state",
  movementsTableErrorClassName: "p-supplier-overview__movements-error",
  movementErrorClassName: "p-supplier-overview__movements-error",
  getMovementKey: (movement, index) => movement?.id || index,
};
